---
- hosts: all
  become: yes

  tasks:

    - name: Install APT packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages: "{{ lookup('file', '../packages.txt').splitlines() }}"

